version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: renewable_energy_app
      MYSQL_USER: sid1
      MYSQL_PASSWORD: dbpassword
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql                                     
      - db-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  api:
    build: ./api
    depends_on:
      - db                    
    volumes:
      - ./api:/code
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://sid1:dbpassword@db/renewable_energy_app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  db-data:
